development:
  adapter: postgresql
  encoding: unicode
  database: todolist_development
  pool: 5
  username: postgres
  password: 'root'

test:
  adapter: postgresql
  encoding: unicode
  database: todolist_test
  pool: 5
  username: postgres
  password: 'root'

production:
  adapter: postgresql
  encoding: unicode
  database: todolist_production
  pool: 5
  host: localhost
  username: postgres
  password: 'root'
